# MONITORS
monitor=,preferred,auto,auto

# WINDOWS, MONITORS AND WORKSPACES
workspace = 1, monitor:HDMI-A-1, default:true
workspace = 2, monitor:DP-3, default:true
workspace = 3, monitor:DP-3
workspace = 4, monitor:DP-3
workspace = 5, monitor:DP-3

workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1

windowrule { 
  name = picture-in-picture
  match:title = ^[Pp]icture\\s*-?\\s*[Ii]n\\s*-?\\s*[Pp]icture$
  
  float = true
  pin = true
  move = ((monitor_w-window_w)-10) ((monitor_h-window_h)-10)
  workspace = 2
}

device {
    name = wacom-hid-521c-finger
    enabled = false
}

device {
    name = hid-256c:006d
    output = DP-3
}
