# WINDOWS, MONITORS AND WORKSPACES
workspace = 1, monitor:eDP-1, default:true
monitor = eDP-1, preferred, auto, 1.25

windowrule { 
  name = picture-in-picture
  match:title = ^[Pp]icture\\s*-?\\s*[Ii]n\\s*-?\\s*[Pp]icture$
  
  float = true
  pin = true
  move = ((monitor_w-window_w)-10) ((monitor_h-window_h)-10)
  workspace = 1
}
