windowrule { 
  name = ignore-max
  match:class = .*
  suppress_event = maximize
}

windowrule { 
  name = xwayland-drag-fix
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1

  no_focus = true
}

windowrule { 
  name = discord
  match:class = ^(discord)$

  workspace = 10
}
