# Theming
font: Inconsolata Nerd Font 12
background: "#282828CC"
color: "#ebdbb2"
separator: " ➜ "
border_width: 0
corner_r: 8
padding: 16
rows_per_column: 4
column_padding: 24
anchor: center
inhibit_compositor_keyboard_shortcuts: true
auto_kbd_layout: true

menu:
  - key: "p"
    desc: Power
    submenu:
      - key: "s"
        desc: Sleep
        cmd: systemctl suspend
      - key: "r"
        desc: Reboot
        cmd: reboot
      - key: "o"
        desc: Off
        cmd: poweroff
  - key: "b"
    desc:
    submenu:
      - key: "e"
        desc: Browser - brave
        cmd: uwsm app -- brave
      - key: "l"
        desc: 3D model - blender
        cmd: uwsm app -- blender
      - key: "m"
        desc: Bluetooth - blueman
        cmd: uwsm app -- blueman-manager
      - key: "o"
        desc: API Client - bruno
        cmd: uwsm app -- bruno
  - key: "d"
    desc:
    submenu:
      - key: "b"
        desc: DB Client - dbeaver
        cmd: uwsm app -- dbeaver
      - key: "c"
        desc: Discord
        cmd: uwsm app -- discord
      - key: "t"
        desc: Devtools
        cmd: uwsm app -- devtoolbox
  - key: "f"
    desc: File Manager - pcmanfm
    cmd: uwsm app -- pcmanfm
  - key: "g"
    desc: Game Engine - godot
    cmd: uwsm app -- godot
  - key: "o"
    desc:
    submenu:
      - key: "b"
        desc: Notes - obsidian
        cmd: uwsm app -- obsidian
      - key: "s"
        desc: Broadcast - obs
        cmd: uwsm app -- obs
  - key: "t"
    desc: Terminal - kitty
    cmd: uwsm app -- kitty
